export const CUSTOM_PRODUCTS = "CUSTOM_PRODUCTS";
export const CUSTOM_PRODUCT_KIT_IDS = "CUSTOM_PRODUCT_KIT_IDS";
export const CUSTOM_PRODUCT_KIT_ITEM_LIST = "CUSTOM_PRODUCT_KIT_ITEM_LIST";

export const STARTER_KITS_ITEMS = "STARTER_KITS_ITEMS";
export const ADDONS_KITS_ITEMS = "ADDONS_KITS_ITEMS";
